<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ScweenSpit</RootNamespace>
    <AssemblyName>ScweenSpit</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <!-- single-file publish: dotnet publish -c Release -r win-x64 -->
    <SelfContained>false</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

</Project>
